### ISSUE TITLE
Restrict submission of duplicate VCFs

### ISSUE THREAD

**Issue by arahuja** [hammerlab/cycledash#103]
It's currently possible for a user to submit a VCF path twice.  Since the VCF is always the latest version, loaded directly from HDFS, I don't think there is ever a reason for a user to submit a VCF twice other than by mistake (which happens now when we re-run a ketrew pipeline that has already completed).  Can we restrict a VCF from being sumbitted twice to clean up the 'runs' page from duplicates?  (Preferably a quiet error/warning)

**Comment by danvk** [comment]
@ihodes was this fixed? I vaguely remember getting an error about duplicate VCF files while testing sometime in the last few months.

**Comment by ihodes** [comment]
This has been fixed.
