### ISSUE TITLE
Kill the diamond "loading" pattern in BioDalliance

### ISSUE THREAD

**Issue by danvk** [hammerlab/cycledash#152]
This appears when there are too few short reads to fill the vertical space. It's ugly:
![screen shot 2014-10-23 at 6 48 34 pm](https://cloud.githubusercontent.com/assets/98301/4762762/c4b38a6a-5b06-11e4-8a17-22ff30d123d9.png)

It can be replaced with a plain white background. This is what IGV does.

**Comment by ihodes** [comment]
wontfix, will be fixed when pileup.js is integrated
