### ISSUE TITLE
Karyogram: restrict zooming out to a reasonable point

### ISSUE THREAD

**Issue by ihodes** [hammerlab/cycledash#159]
Currently, one can zoom out infinitely: this isn't great.

![](http://cl.ly/image/1X3e0W431c2g/Screen%20Shot%202014-10-27%20at%205.42.26%20PM.png)

**Comment by danvk** [comment]
@ihodes do you expect we'll add support for the karyogram back at some point? or shall we close these issues out?

**Comment by ihodes** [comment]
@dan good call; going to close this. If we decide a karyogram is on the roadmap at some point, we can reopen.
