### ISSUE TITLE
Biodalliance position does not match selected variant

### ISSUE THREAD

**Issue by arahuja** [hammerlab/cycledash#202]
In Chrome:

![image](https://cloud.githubusercontent.com/assets/455755/5032904/9350607c-6b2f-11e4-902f-8a9c30cf3cc9.png)

In Safari, this *was* not the case on first click, but now is:

![image](https://cloud.githubusercontent.com/assets/455755/5032919/bbee5516-6b2f-11e4-8301-1beb8ae22b84.png)

If I refresh, refilter and try again it works:
![image](https://cloud.githubusercontent.com/assets/455755/5032924/d03097aa-6b2f-11e4-803e-970a83ee84e1.png)

**Comment by arahuja** [comment]
Finally ran into this issue again:

![image](https://cloud.githubusercontent.com/assets/455755/5651347/a70094a0-9674-11e4-94fb-3f3e16c06e38.png)

**Comment by ihodes** [comment]
wontfix/not an issue/pileup.js is replacing biodalliance
