### ISSUE TITLE
Implement Karyogram

### ISSUE THREAD

**Issue by ihodes** [hammerlab/cycledash#245]
This may depend on #243.

![](http://f.cl.ly/items/3w1x130H022f102x0A0Q/Screen%20Shot%202014-10-27%20at%2010.54.37%20AM.png)

**Comment by hammer** [comment]
cf. @ryan-williams's design http://cl.ly/image/1f3M3b1x2q3g

**Comment by ihodes** [comment]
Closing this; can reopen if we decide to re-add the karyogram.
