### ISSUE TITLE
Support more contig names in range queries

### ISSUE THREAD

**Issue by danvk** [hammerlab/cycledash#258]
Currently contig names have to be `[0-9]+|X|Y`. hg19 uses a `chr` prefix for all its contigs, so this doesn't work there. It also prevents you from querying the `GTXXX` contigs.

Regardless, we should support something like `CONTIG = chr19` as an escape hatch.

**Comment by ihodes** [comment]
This works now.

**Comment by danvk** [comment]
To be clear, the "escape hatch" exists (you can query `CONTIG = chr13`), but the simpler range syntax (`chr13:1234-4567`) still doesn't parse.
