### ISSUE TITLE
Add worker status to examine page

### ISSUE THREAD

**Issue by tavinathanson** [hammerlab/cycledash#280]
For example:

"Currently extracting genotypes..."
"Currently annotating genes..."
"Done"

**Comment by ihodes** [comment]
Should (also?) probably be on the /runs page.

**Comment by ihodes** [comment]
cf. https://github.com/hammerlab/cycledash/issues/241

**Comment by danvk** [comment]
@ihodes thoughts on how to do this? Is it possible to query the state of the workers? Do we need a convention of workers updating another DB table?

**Comment by ihodes** [comment]
A state machine in the DB seems like the way to do this. The table should probably have a column for each worker than can be run, with a state in each.

**Comment by danvk** [comment]
Is it not possible to query the workers? My concern is that workers updating the DB to reflect their own state is going to be really error prone. For example: the indexer worker records that it's started. Then it throws an exception and is listed as "running" forevermore.

**Comment by ihodes** [comment]
It may be possible; I haven't looked into it.

Re: updating the DB, the workers could be wrapped in a try block to catch any exception and at least update the DB before crashing.

**Comment by danvk** [comment]
Looks like it is possible: http://stackoverflow.com/questions/9034091/how-to-check-task-status-in-celery

To make this approach work, we'd add a new table mapping vcf_id→[celery task_id]. When you viewed the runs page, we could check up on all the workers.

**Comment by ihodes** [comment]
Does this mean we'd need to query all the celery tasks? M tasks for worker, N workers, MxN total queries (though most of them would hopefully be completed). Could be good to still store some status of a worker in the DB.

**Comment by danvk** [comment]
Agreed. If we stored a STATUS field along with the VCF→[task_id] mapping, we'd only need to re-query the running tasks.

**Comment by danvk** [comment]
OK, here we go!
