### ISSUE TITLE
submitting a new run seems to do nothing

### ISSUE THREAD

**Issue by timodonnell** [hammerlab/cycledash#335]
I submitted this run this weekend and also today using the "post a new run" link. Both times the submission seems to go through, but I never see it show up on the runs page.

hdfs://demeter-nn1.demeter.hpc.mssm.edu/user/odonnt02/PT189-ovarian/PT189.conservative.vcf

If this is throwing an error while loading the VCF into the DB, may be worth considering a way for those errors to percolate back to users (perhaps an /errors page with the latest error errors?) Just a thought.

**Comment by ihodes** [comment]
This appears to have been a residual issue (from a queue crash) that no longer occurs.
