### ISSUE TITLE
Dalliance doesn't show the reference genome initially

### ISSUE THREAD

**Issue by danvk** [hammerlab/cycledash#391]
On run 173, when I open Dalliance for the first of the two variants, I see this:

![screen shot 2014-12-15 at 12 28 18 pm](https://cloud.githubusercontent.com/assets/98301/5440382/e6cc3c3c-8455-11e4-8268-b36377332e6e.png)

The reference track is empty. If I hit the zoom out button once, I see it:
![screen shot 2014-12-15 at 12 31 01 pm](https://cloud.githubusercontent.com/assets/98301/5440427/45e6ac84-8456-11e4-8140-b3056a710ab6.png)

If I zoom back in, I still see the reference, so this may just be dalliance flakiness, rather than anything to do with the zoom level.

**Comment by ihodes** [comment]
No longer using dalliance, closing
