### ISSUE TITLE
autocomplete dataset name

### ISSUE THREAD

**Issue by arahuja** [hammerlab/cycledash#4]
To ensure that entries that are made on the same dataset match in dataset name can we have this autocomplete or as a dropdown as already submitted options + new?

**Comment by arahuja** [comment]
Gonna re-request this! Also if we fill in a dataset, can it fill in the BAM paths as well

**Comment by ihodes** [comment]
Yeah it's about time to add this! Using this https://github.com/hammerlab/cycledash/blob/master/cycledash/static/js/CompletionUtils.js and the React.js rewrite of the /runs page pending in PR #450, this should be easy.
