### ISSUE TITLE
Create a public demo

### ISSUE THREAD

**Issue by danvk** [hammerlab/cycledash#431]
It could run on Heroku or EC2. It would be helpful to link off to when discussing CycleDash on the blog.

**Comment by hammer** [comment]
I think we can do this later. I think a screencast is fine for now.

**Comment by ihodes** [comment]
done at ec2-54-148-116-242.us-west-2.compute.amazonaws.com:5000

**Comment by jaclynperrone** [comment]
Looks like the amazon link has died. Can we resurrect this?
