### ISSUE TITLE
Indicate when run's files don't exist

### ISSUE THREAD

**Issue by ryan-williams** [hammerlab/cycledash#440]
Currently runs 204 and 205 give me different "INTERNAL SERVER ERRORS" when I try to examine them:

![image](https://cloud.githubusercontent.com/assets/465045/5943645/baedfd06-a6ee-11e4-91de-21fd6c1acfa6.png)

![image](https://cloud.githubusercontent.com/assets/465045/5943651/d44f0362-a6ee-11e4-9df3-80cb9d126aba.png)

It would be nice if:
* the homepage indicated this in some way
* the homepage allowed for removing or otherwise didn't display such runs
* the examine page, if still possible to navigate to, indicated this more gracefully

**Comment by ihodes** [comment]
Related to #362. We shouldn't show the user an [Examine] button if there's nothing to examine.

**Comment by ryan-williams** [comment]
211 has given me a mix of the blank page ISE above as well as a third "phenotype" where the page seems to load but doesn't display any info or error msgs:

![image](https://cloud.githubusercontent.com/assets/465045/5943807/0ba5c408-a6f0-11e4-8113-3b2b94dcf0d8.png)
