### ISSUE TITLE
Document CQL grammar

### ISSUE THREAD

**Issue by hammer** [hammerlab/cycledash#442]
Bonus points for [railroad diagrams](http://julianhyde.blogspot.com/2009/05/clapham-railroad-diagram-generator.html)

**Comment by ihodes** [comment]
Have had good luck using this to generate RR diagrams: http://www.bottlecaps.de/rr/ui

**Comment by danvk** [comment]
Is [this](https://github.com/hammerlab/cycledash/wiki/CQL-(CycleDash-Query-Language)) not sufficient? It's linked to from the CQL box itself, so it should be easy to find.

**Comment by hammer** [comment]
oh whoops that is probably sufficient!
