### ISSUE TITLE
cycledash right .bai.json file with username = `username`

### ISSUE THREAD

**Issue by arahuja** [hammerlab/cycledash#453]
Is this the intended behavior?  It seems the `.bam.bai.json` file is created a username = `username`

```
-rwxr-xr-x   3 username supergroup        528 2015-02-16 21:31 /datasets/.../...bam.bai.json
```

**Comment by danvk** [comment]
It's coming from `ENV.sh`:

```
$ grep WEBHDFS /home/cycledash/cycledash/ENV.sh
export WEBHDFS_USER=username
export WEBHDFS_URL='http://demeter.hpc.mssm.edu:14000'
```

@ihodes can you see any harm in changing this to, say, `cycledash`?

**Comment by ihodes** [comment]
Not at all; I'm pretty amused that it can just be called anything (really?) and it'll work.

**Comment by arahuja** [comment]
Does this mean that cycledash needs write permission to the folder and which user would that be (that needed the permissions?)

**Comment by arahuja** [comment]
@ihodes yea that seems pretty weird - I would've thought a proper user needed to exist

**Comment by danvk** [comment]
I changed `WEBHDFS_USER` to `cycledash`. LMK if things are better/worse.
