### ISSUE TITLE
allow user to manage space allocation of the pileup and list of variants panes

### ISSUE THREAD

**Issue by timodonnell** [hammerlab/cycledash#461]
Low priority. The list of variants pane gets pretty cramped when showing a pileup, and it's hard to write a comment. It would be helpful if the user could resize the pileup pane to give more room to the top pane, or pop out the pileup view to a separate window.

![image](https://cloud.githubusercontent.com/assets/467896/6272834/cfa0791c-b838-11e4-9d63-79db19dff5c9.png)

**Comment by danvk** [comment]
This is obsolete—as of #721 we're going with either full page variants list or full page pileup. No more space management.
