### ISSUE TITLE
NT column in info field is not parsed out

### ISSUE THREAD

**Issue by arahuja** [hammerlab/cycledash#471]
`INFO` field looks like 
```
QSS_ref NT=hom;QSS=55;QSS_NT=55;SGT=GG->GT;SOMATIC;TQSS=1;TQSS_NT=1
```

NT is not showing as a column, but QSS and on are.

**Comment by ihodes** [comment]
I was wondering about that; isn't `QSS_ref NT=…` invalid syntax?

**Comment by arahuja** [comment]
It exists in the output of a top variant caller, so we may need to stretch our definiton of valid.

**Comment by ihodes** [comment]
Valid point.

**Comment by arahuja** [comment]
Nevermind, I had read this output incorrectly.  The `INFO` field is just `NT=hom;QSS=55;QSS_NT=55;SGT=GG->GT;SOMATIC;TQSS=1;TQSS_NT=1` and `NT` is not appearing

**Comment by ihodes** [comment]
Can you link to a problematic VCF?

**Comment by arahuja** [comment]
An example is at `/runs/225/` on the internal cycledash page

**Comment by arahuja** [comment]
The QSS_ref issue is really #473
