### ISSUE TITLE
Display FILTER field in a VCF

### ISSUE THREAD

**Issue by arahuja** [hammerlab/cycledash#473]
For an example VCF
```
chr1    12907620        .       A       G       .       PASS    ....
chr1    12920828        .       C       A       .       QSS_ref ...
```

The 7th field is the `FILTER` field which is not visible in Cycledash currently

**Comment by timodonnell** [comment]
Does cycle dash use varcode to open VCF's? If it does, then I have a varcode branch that preserves the FILTER field (currently it throws it out, which might be why cycledash doesn't show it). I can get that into master soon if needed

**Comment by ihodes** [comment]
Cycledash uses PyVCF, which does indeed extract filters, we're just not saving them right now.

**Comment by ihodes** [comment]
For whomever implements this: the filter field should probably be put in an "annotations:FILTERS" field, which will take care of the CQL interaction + display on the examine page.
