### ISSUE TITLE
> 0 gives >= 0

### ISSUE THREAD

**Issue by ihodes** [hammerlab/cycledash#474]
![](https://s3.amazonaws.com/f.cl.ly/items/0n2E0o121P452E2U1y0p/Screen%20Shot%202015-02-27%20at%2012.01.17%20AM.png)

**Comment by danvk** [comment]
`sample:GT` a string column, so it's behaving correctly. For example:
![screen shot 2015-03-03 at 11 22 36 am](https://cloud.githubusercontent.com/assets/98301/6466719/a786da44-c197-11e4-8ca4-80f642794c63.png)
