### ISSUE TITLE
Allow datasets to be annotated

### ISSUE THREAD

**Issue by ihodes** [hammerlab/cycledash#475]
E.g. in Confluence we have a table of datasets with things like "notes", "date of resection", "location of sample", etc. We should support that in CycleDash, on the /runs page.

**Comment by ihodes** [comment]
Should also have the flagstat info cf. https://github.com/hammerlab/cycledash/issues/468

**Comment by hammer** [comment]
Cf. [triple tags](http://en.wikipedia.org/wiki/Tag_(metadata)#Triple_tags)
