### ISSUE TITLE
Fix variant counter

### ISSUE THREAD

**Issue by arahuja** [hammerlab/cycledash#489]
Two issues here:

1. It's not obvious what the counter is counting.  It looks like it's total genotypes or total variants * samples.  This is confusing when they are somatic variants and you want to use the filters.  Filtering to the tumor sample  will usually work, but maybe you want to remove somatic variants based on properties of the normal which isn't currently possible.

2. If the VCF had duplicates the counter counts them, but they are not displayed, see screen shot:

![image](https://cloud.githubusercontent.com/assets/455755/6433376/5d985668-c03b-11e4-8f35-ced8e3e13aa5.png)

**Comment by ihodes** [comment]
This appears to be a problem for this particular run because the genotype extractor was run twice on it (queue crashed?) Going to close this in favor of https://github.com/hammerlab/cycledash/issues/250
