### ISSUE TITLE
Impossible stats

### ISSUE THREAD

**Issue by danvk** [hammerlab/cycledash#516]
The stats say "showing all 10 variants", but the numbers add up to 20:
![screen shot 2015-03-05 at 12 14 06 pm](https://cloud.githubusercontent.com/assets/98301/6510027/40f3c7d8-c331-11e4-824e-0229ff73d7a4.png)

There are only ten rows in the VCF table:
![screen shot 2015-03-05 at 12 15 34 pm](https://cloud.githubusercontent.com/assets/98301/6510036/5f2bf572-c331-11e4-9e22-2bc812a98a35.png)

I assume this has something to do with the warnings React is flagging:
![screen shot 2015-03-05 at 12 16 16 pm](https://cloud.githubusercontent.com/assets/98301/6510049/73a114c4-c331-11e4-8798-8258c4181989.png)

**Comment by ihodes** [comment]
cf https://github.com/hammerlab/cycledash/issues/571

**Comment by ihodes** [comment]
cf. https://github.com/hammerlab/cycledash/issues/588
