### ISSUE TITLE
Random autocompletes

### ISSUE THREAD

**Issue by arahuja** [hammerlab/cycledash#524]
Why are these options shown in the autocomplete?
![image](https://cloud.githubusercontent.com/assets/455755/6563192/86e712da-c675-11e4-8c25-0b9230639461.png)

Even more, it changes as I go from "stand" to "standard" but none actually match (in a way that I can tell)

**Comment by danvk** [comment]
I think you're running into the fuzzy matching—it's really looking for
/.*s.*t.*a.*n.*d.*a.*r.*d.*/ -- with lots of long caller names, it's not
surprising that some match that. Maybe we should only show substring
matches if they exist.

**Comment by arahuja** [comment]
But `guacamole: somatic-standard` which what I was looking for was not coming up?
