### ISSUE TITLE
Submit forms via AJAX & Display Errors Nicely

### ISSUE THREAD

**Issue by ihodes** [hammerlab/cycledash#530]
On the runs page.

AKA, from @iskandr, "Client-side form validation for submitting a New Run"

**Comment by jaclynperrone** [comment]
@ihodes Will this take care of the need to refresh the page after a file upload? Or should I file a separate issue for that?

**Comment by ihodes** [comment]
Yes, this should fix that issue.

**Comment by ihodes** [comment]
Errors not "nice" per say, but fixed & filed an issue for making the errors nicer still.

https://github.com/hammerlab/cycledash/pull/617
