### ISSUE TITLE
Help text is too close to IGV text

### ISSUE THREAD

**Issue by tavinathanson** [hammerlab/cycledash#544]
![image](https://cloud.githubusercontent.com/assets/322932/6674700/fdc21004-cbf1-11e4-9ded-ef86ae7cd7ee.png)

Right?

**Comment by hammer** [comment]
I agree that design looks funny to me too. It was also not clear to me that the "Load at Locus" and "Jump" were two separate commands; my first read was that "Jump" was a paraphrase of the longer "Load at Locus".

**Comment by hammer** [comment]
Also I think using a question mark icon is probably better than the word "help".

**Comment by ihodes** [comment]
cf. http://thenounproject.com/term/question-mark/33699/

**Comment by tavinathanson** [comment]
The winner, clearly: 
![image](https://cloud.githubusercontent.com/assets/322932/6674779/80597796-cbf2-11e4-99f9-236c4ffb6935.png)

**Comment by danvk** [comment]
Would it help to underline the links?

![screen shot 2015-03-16 at 3 45 00 pm](https://cloud.githubusercontent.com/assets/98301/6674909/709a6350-cbf3-11e4-9672-88c421f47209.png)

**Comment by hammer** [comment]
Another strong contender: http://thenounproject.com/term/question-mark/33699/

**Comment by ihodes** [comment]
This has been fixed. cf. http://d.pr/i/9QxW
