### ISSUE TITLE
Client-side form validation for submitting a New Run

### ISSUE THREAD

**Issue by iskandr** [hammerlab/cycledash#545]
When I try to submit a new run without filling in any of the fields I get back the JSON text of an error: 

```
{
  "error": "Run validation", 
  "message": "required key not provided @ data['variant_caller_name']"
}
```

...it wouldn't be nicer to instead see the required fields within the form UI and get a nicer error message.

**Comment by ihodes** [comment]
Totally agreed, dup of https://github.com/hammerlab/cycledash/issues/530
