### ISSUE TITLE
"Bumping limit exceeded" dalliance error

### ISSUE THREAD

**Issue by ryan-williams** [hammerlab/cycledash#546]
Seeing this [here](http://cycledash.demeter.hpc.mssm.edu/runs/225/examine?query=chr7%3A100550079-100550080+ORDER+BY+contig%2C+position):

![](https://s3.amazonaws.com/f.cl.ly/items/3b3s1e2g1A230c070F3z/Screen%20Shot%202015-03-17%20at%202.40.28%20PM.png)

Missing reference from #391 also happening.

After zooming out and back in, the BAMs seem to be in some half-loaded state, though I do have the reference track:

![](https://s3.amazonaws.com/f.cl.ly/items/0m3L30062H0m0F331n2y/Screen%20Shot%202015-03-17%20at%202.44.04%20PM.png)

**Comment by danvk** [comment]
Yeah, I have no idea what a bumping limit is. Maybe something to do with an especially deep pileup?

**Comment by ryan-williams** [comment]
ported to dalliance.
