### ISSUE TITLE
Can't zoom in after zooming out

### ISSUE THREAD

**Issue by ryan-williams** [hammerlab/cycledash#547]
I opened a variant on [this run](http://cycledash.demeter.hpc.mssm.edu/runs/141/examine?query=ORDER+BY+contig%2C+position) in dalliance:

![](https://s3.amazonaws.com/f.cl.ly/items/253J3z2D231e2j0I2j0t/Screen%20Shot%202015-03-17%20at%202.53.09%20PM.png)

I clicked "zoom out" to try to get rid of the "Bumping" error message:

![](https://s3.amazonaws.com/f.cl.ly/items/310I0i04210s293o3l0E/Screen%20Shot%202015-03-17%20at%202.53.42%20PM.png)

Clicking "zoom in" immediately after seems to no-op. Why is that?

Separately: can we disable zoom buttons when they won't do anything?

**Comment by danvk** [comment]
I have no idea what bumping is.

I think what's going on here is that Dalliance won't let you zoom in closer than 200bp via the UI. When you open the pileup viewer via the link, it zooms to a 50bp region using the Dalliance API, which doesn't have this restriction. If you close dalliance & reopen it using the link, it should reset the view.

**Comment by ryan-williams** [comment]
ported to dalliance issue ^^
