### ISSUE TITLE
Only alternating rows are highlighted in yellow

### ISSUE THREAD

**Issue by tavinathanson** [hammerlab/cycledash#549]
Compare:

![image](https://cloud.githubusercontent.com/assets/322932/6699584/b198de54-ccd9-11e4-9d6c-c427d4f739b3.png)

![image](https://cloud.githubusercontent.com/assets/322932/6699586/b3ecac9e-ccd9-11e4-81fe-39e53ff13ffd.png)

**Comment by jaclynperrone** [comment]
This was fixed in PR #640
