### ISSUE TITLE
Set up a sample version of CycleDash somewhere publicly accessible

### ISSUE THREAD

**Issue by hammer** [hammerlab/cycledash#565]
Pravin wants to mess around.

**Comment by hammer** [comment]
@ihodes @danvk we have a potential user of CycleDash at Cloudera as well; any chance you guys could get this set up early next week?

**Comment by ihodes** [comment]
Sounds good! May not have streaming BAMs right away (right now we stream them off of HDFS).

Notes for me:
1) Cycledash deploy 
2) Celery required e.g. amq
3) Postgres server
4) Bonus: set up streaming BAMs.

**Comment by hammer** [comment]
HDFS has a single-process mode called "local" or "standalone" that you could use for this purpose.

**Comment by ihodes** [comment]
Awesome, good to know; that'll make things a bit easier.

**Comment by ihodes** [comment]
Done @ http://ec2-54-148-116-242.us-west-2.compute.amazonaws.com:5000/

[Need to put some BAMs on there--the hadoop binaries (for local HDFS) are on the EC2 instance, but there may be some classpath issues preventing them from working.]
