### ISSUE TITLE
"Last 5 Comments" has a text wrap issue in the pdifftest screenshots

### ISSUE THREAD

**Issue by tavinathanson** [hammerlab/cycledash#569]
@danvk noticed that there's an issue with text wrap in the "Last 5 Comments" table showing up in runs_info.png.

![image](https://cloud.githubusercontent.com/assets/322932/6946515/dda467de-d86e-11e4-9ea9-9efdccc36c2e.png)

**Comment by ihodes** [comment]
These wrap more appropriately now (cf. current https://raw.githubusercontent.com/hammerlab/cycledash/master/tests/pdifftests/images/runs_page.png); we also have https://github.com/hammerlab/cycledash/issues/650 to track improving this.
