### ISSUE TITLE
IGV integration broken

### ISSUE THREAD

**Issue by danvk** [hammerlab/cycledash#574]
BAM tracks wouldn't load during the demo w/ the plot.ly folks today. Some kind of regression?

**Comment by arahuja** [comment]
I couldn't find a working example today - was this a real issue?

**Comment by danvk** [comment]
Yeah, it is. I'll debug now.

**Comment by danvk** [comment]
http://cycledash.demeter.hpc.mssm.edu/runs/270 illustrates some of the problems.

One issue is that the VCF file for that run doesn't end in `.vcf` (it's `/foo.vcf/part-r-00000`). IGV switches track type on the file extension, so it has no idea what it's looking at.

I'm not sure why the BAM files aren't being included in the URL yet.

**Comment by danvk** [comment]
The issue with BAMs is that `run.normal_bam.uri` and `run.normal_bam.uri` got dropped at some point and none of the tests were strong enough to catch it. @ihodes does that sound familiar? Maybe part of the reorganization of the /runs page?

**Comment by ihodes** [comment]
Probably so; I don't recall the particulars.

**Comment by danvk** [comment]
The /runs page generates a "run" object through `_get_projects_tree`.
The /examine page generates it through `runs.get_vcf`.

One solution is to have `runs.get_vcf` call `_get_projects_tree` and find the relevant VCF. This will pull in more data than is necessary, but it will result in a more uniform run/vcf object.

**Comment by danvk** [comment]
#591 fixes the missing BAM issue.

The only workaround I can see for the VCF issue is to serve the VCF through cycledash itself with a different suffix. @arahuja would requiring that VCFs have the right extension be an undue burden?

**Comment by danvk** [comment]
A separate issue is that IGV requires an index for sufficiently large VCF files. This happens on run 189, for instance, where it issues a request for the non-existent  `http://hammerlab-dev3.hpc.mssm.edu:9876/datasets/martignetti_ovarian/189/Ion_Exome/TSVC_variants_IonXpress_019.vcf.idx`. The VCF is 30+ MB. I wasn't aware that there was a standard index format for VCFs!

**Comment by danvk** [comment]
See https://github.com/igvteam/igv/issues/146

**Comment by danvk** [comment]
The IGV people are going to fix the VCF extension issue upstream. Once that happens I'll use the fix & we can close this out.

**Comment by arahuja** [comment]
To be honest, having IGV show the variant is not that critical - since we are only selecting positions where there is a variant, the additional box that signifies it doesn't add much. 

The one advantage would be that you can jump to the next variant or see how far the next variant is, but loading the BAMs is what I'm interested in most of the time

**Comment by arahuja** [comment]
Oh great - well that solves that - we can set up a way to index them as well pretty easily I think.

**Comment by danvk** [comment]
The IGV people have fixed this upstream already (!). Once a new release rolls out (in the next week or so), I'll add the `&format=` parameter to the IGV URL.

**Comment by ihodes** [comment]
@danvk did the IGV folks release this update?

**Comment by danvk** [comment]
I believe so. If you have v2.3.53 or newer, you should have support. I'll add the URL parameters this week.
