### ISSUE TITLE
What is the BAM URI check?

### ISSUE THREAD

**Issue by arahuja** [hammerlab/cycledash#577]
I tried submitting a run manually I get:
```
{
error: "BAM not found",
message: "bam with uri "/datasets/tcga/validation/TCGA-DK-A3IN-10A-01D-A210_120911_SN1120_0189_BD1D04ACXX_s_2_rg.sorted.bam" does not exist"
}
```

but it does exist:

```
hadoop fs -ls /datasets/tcga/validation/TCGA-DK-A3IN-01A-11D-A210_120911_SN1120_0189_BD1D04ACXX_s_1_rg.sorted.bam
-rw-r--r--   3 hammej03 supergroup 34412207027 2015-03-01 21:39 /datasets/tcga/validation/TCGA-DK-A3IN-01A-11D-A210_120911_SN1120_0189_BD1D04ACXX_s_1_rg.sorted.bam
[
```

**Comment by ihodes** [comment]
Try submitting the BAM first, then submit the run with the BAM. 

This is the only way I could think to capture metadata about BAMs consistently. If we don't care much about BAM metadata in the common case, I can just automatically insert a BAM into the database when an previously unencountered BAM is submitted with a run. The downside is we wouldn't be capturing any metadata about the BAM at all.

**Comment by arahuja** [comment]
Yea, submitting the bam first worked - but when I tried it yesterday, I submitted the BAM uri's prepended with `hdfs` as that is in the filler text:
![image](https://cloud.githubusercontent.com/assets/455755/7006676/02d7fdb4-dc51-11e4-9181-e9a14efa94c8.png)

But that isn't necessary? or just that it should the same in both submissions?

**Comment by arahuja** [comment]
I think updating the error message to say something like submit the bam first would be helpful

**Comment by ihodes** [comment]
Definitely agree. Our error message story is pretty poor right now. #willfix :)

**Comment by ihodes** [comment]
fixed with https://github.com/hammerlab/cycledash/pull/617
