### ISSUE TITLE
Comment text box shouldn't be horizontally resizable

### ISSUE THREAD

**Issue by tavinathanson** [hammerlab/cycledash#579]
(Very minor...)

![screen shot 2015-04-13 at 1 57 34 pm](https://cloud.githubusercontent.com/assets/322932/7121801/0ead30a2-e1e5-11e4-894e-810e32674785.png)

**Comment by ihodes** [comment]
This doesn't seem like a bug; in the insanely rare case a user wants to expand the field, why stop them? The comment field is normally sized appropriately. This will also be changed once https://github.com/hammerlab/cycledash/issues/650 is done. 

What say you to closing this, @tavinathanson?

**Comment by tavinathanson** [comment]
No strong feelings on this one. Close I shall.

**Comment by ihodes** [comment]
Thank you I do.
