### ISSUE TITLE
/upload gives "Method Not Allowed"

### ISSUE THREAD

**Issue by arahuja** [hammerlab/cycledash#585]
Does this feature still exist? Is there a way to do this through the API still? The biokepi scripts were relying on this.

**Comment by ihodes** [comment]
I'm having trouble remembering: was this to upload a VCF? That functionality is there still, if so. I'll unearth it tomorrow if that's what you're looking for.

**Comment by ihodes** [comment]
@arahuja Any update on this not working? It appears to be working for me and @smondet—can you describe how to reproduce this?

**Comment by smondet** [comment]
I haven't tried in a while (have been mostly running pre-VCF stuff lately)

**Comment by ihodes** [comment]
Good to know—I'll check the upload script while rewriting it for the new API. It may well have broken somehow.

**Comment by ihodes** [comment]
This appears to be working for me (same invocation is in the biokepi script):

> curl -f -F file=@/Users/isaachodes/Desktop/badvcf.vcf cycledash.demeter.hpc.mssm.edu/upload

Please reopen if this is still an issue.
