### ISSUE TITLE
/about and API.md disagree on VCF parameter

### ISSUE THREAD

**Issue by arahuja** [hammerlab/cycledash#586]
/about says `uri` while the [API.md](https://github.com/hammerlab/cycledash/blob/master/API.md) page says `vcfUri` 

![image](https://cloud.githubusercontent.com/assets/455755/7507873/d7ae1888-f444-11e4-89a8-351d5fa82348.png)

**Comment by ihodes** [comment]
Oh boy, super early to run into dicord in docs. 




We need to generate /about from our API.md.

**Comment by danvk** [comment]
The real solution here is to fix #534. No two things will ever stay in sync unless it's enforced, or there's a common source.
