### ISSUE TITLE
True Positive = 2 but only one check mark on a row

### ISSUE THREAD

**Issue by arahuja** [hammerlab/cycledash#588]
![image](https://cloud.githubusercontent.com/assets/455755/7508172/7d0746a2-f449-11e4-9c30-cc20d268c130.png)

There are 14 rows in this set so the total count is correct, but it says 2 True and 12 False while there is only one check mark.

**Comment by danvk** [comment]
@ihodes want to look into this? There may have been a regression with react keys and table rows.
