### ISSUE TITLE
Misparsed VCF REF→ALT column

### ISSUE THREAD

**Issue by danvk** [hammerlab/cycledash#615]
http://cycledash.demeter.hpc.mssm.edu/runs/86/examine?query=ORDER+BY+contig%2C+position

`C	→	C[11:128639[`

![slack-imgs com](https://cloud.githubusercontent.com/assets/98301/7686683/a1cda600-fd65-11e4-8a8a-b60d3284b0fd.png)

**Comment by ihodes** [comment]
This is correctly parsed; this is one way that VCFs encode structural variants. 

cf. https://samtools.github.io/hts-specs/VCFv4.2.pdf

cf. http://d.pr/i/yiwN
