### ISSUE TITLE
Consolidate IGV links

### ISSUE THREAD

**Issue by danvk** [hammerlab/cycledash#618]
The two IGV links ("load" and "jump") turn out to be unnecessary. If the tracks are already loaded in IGV, reloading them is really fast.

cc @jaclynperrone

**Comment by hammer** [comment]
Should we just deprecate the links to IGV now that we have control over pileup visualizations?

**Comment by danvk** [comment]
They're still useful—there's a lot IGV can do that pileup can't, and that's likely to be true for a long time to come. Unless we do a 10-person sprint on it :)

**Comment by hammer** [comment]
Fair enough. I filed https://github.com/hammerlab/cycledash/issues/619 so we can document missing IGV features when we encounter them.
