### ISSUE TITLE
Show subobjects in JSON responses

### ISSUE THREAD

**Issue by ihodes** [hammerlab/cycledash#624]
e.g. instead of `project_id: <id>` on a run, `project: {id: <id>, name: ..., notes: ...}`

**Comment by ihodes** [comment]
This is required for the `run` information provided on the `/examine` page, removing it regressed https://github.com/hammerlab/cycledash/pull/591

**Comment by danvk** [comment]
This shouldn't be closed until there's a regression test for #630

**Comment by ihodes** [comment]
Not sure this is something we really need/want to do in the API.
