### ISSUE TITLE
User interviews

### ISSUE THREAD

**Issue by hammer** [hammerlab/cycledash#629]
# ISMMS
- [x] Michael Linderman
- [ ] Andrew Uzilov
- [ ] Hardik Shah
- [ ] Ming Xue
- [ ] Qichao Zhu
- [ ] Yirong Wang
- [ ] Kathryn Landy

# MSKCC
- [x] Matthew Chang
- [ ] Cyriac Kandoth

# Weill Cornell
- [x] Ken Eng 

# Columbia
- [ ] Josh Bridgers

# NYGC
- [ ] Nicolas Robine

**Comment by hammer** [comment]
@smondet any thoughts on who at NYU might be doing somatic variant calling?

**Comment by hammer** [comment]
Also for those following along at home you can see the results of the completed interviews on [Google Drive](https://drive.google.com/folderview?id=0B1_v1LBEUeoufkg4WjY0S0pxWkt5Mk1sU2g2Z0g0MW1icnQ3NWlZbDBfTkM0Tl9kZTh3NGc&usp=drive_web&tid=0B1_v1LBEUeoufjVVUUtuT3VtWWcxdkZOT0o2LTc5OFl6bFBnbzZJSmduakEtdE9VM3FBVU0).

**Comment by jaclynperrone** [comment]
Michael Linderman gave me Kathryn Landy's contact information. She is a graduate student who works with variant callers.

**Comment by hammer** [comment]
Moved to our internal `projects` project.
