### ISSUE TITLE
Make deploying & updating Cycledash incredibly easy 

### ISSUE THREAD

**Issue by ihodes** [hammerlab/cycledash#633]
Right now, it's not.

This could take the form of a `make`-like command, or maybe something like Docker or Vagrant.

**Comment by jaclynperrone** [comment]
@ihodes Nice! Does this cover installation as well?

**Comment by ihodes** [comment]
I think #803 is going to get us as close as reasonably possible right now. 

Deploying Cycledash consists of cloning the git repository, preparing Postgres & RabbitMQ, setting up a few environment variables in ENV.sh (generated by Make), and running ./scripts/upgrade.sh (and python scripts/init_db.py if this is the initial deployment).

Docker is a little too cutting edge to work for us right now (can't run on CentOS6, for one). Docker-compose is also not yet production ready, and I'm unclear on how clean of a solution it gives us right now. Cf. [this useful HN thread & associated article](https://news.ycombinator.com/item?id=9961537) for some things that need solving.

We can revisit or reopen as it appears necessary to make this even easier.
