### ISSUE TITLE
Pileup.js + Design = fancyPileup.js

### ISSUE THREAD

**Issue by jaclynperrone** [hammerlab/cycledash#647]
Let's talk about the ways in which Pileup.js could benefit from a little design love. Gonna open up this thread to talk about the things IGV does well and not-so-well, and where pileup.js fits in.

**Comment by hammer** [comment]
Possible scope creep: we should decide whether pileup should appear below the variant being examined or if there should be a fixed location for pileup visualization,

**Comment by ihodes** [comment]
Good point; the thinking has shifted towards popping Pileup.js out of the window, and having it communicate with the examine page that way.

**Comment by jaclynperrone** [comment]
Also would be helpful to label which pane belongs to which file (ie Normal BAM, Tumor BAM, VCF)

**Comment by danvk** [comment]
Yeah, see https://github.com/hammerlab/pileup.js/issues/129 for track names.

**Comment by jaclynperrone** [comment]
And see #687 for popping it out on a new window

**Comment by jaclynperrone** [comment]
@danvk and I had a good conversation about this and a bunch of new issues came out of it. Gonna close it!
