### ISSUE TITLE
Comments redesign

### ISSUE THREAD

**Issue by jaclynperrone** [hammerlab/cycledash#650]
Right now the comments are styled in two different ways. They are displayed as list items on the Runs page, and objects on the Examine page. The goal is to pick a direction and make them look consistent throughout the app. I'd like to play around with a timeline/activity feed approach on the Runs page, which may lend itself to how the comments are styled on the Examine page.

**Comment by jaclynperrone** [comment]
Check out #607 , which talks about adding more meta data to the comments on the Runs page

**Comment by jaclynperrone** [comment]
@ihodes @danvk @armish @hammer I'm struggling with the "most recent comments" feed that shows comments across all the projects. I'm thinking that the comments are better served in context with their projects, rather than as separate entities. If I am on the runs page to view my most recent project, why would I want to see comments from past projects that I don't necessarily care about anymore? Would love to hear your thoughts!

**Comment by ihodes** [comment]
I think the purpose of that feature was to keep track of recent activity; if someone makes a comment on an older run today, there's currently no other way to know about it.

**Comment by jaclynperrone** [comment]
I see. Perhaps we can have a way to indicate that on the project level?

**Comment by ihodes** [comment]
How would you see that on an older project? 

A better solution might be a notification system. That is dependent on a account/login/ACL system.

**Comment by jaclynperrone** [comment]
True. That would be ideal. I think for now, since the comments don't mention project name, we could add that extra detail to help with context (cf. #607)

**Comment by ihodes** [comment]
:+1: agreed

**Comment by armish** [comment]
I think both feeds (all comments and comments for a specific project) are helpful. Would be great to show them side by side or allowing users to switch between them with a click ([Show all comments](#) vs. [Show all comments for this project](#)).

:+1: for @ihodes' idea for an account-based notification system.

**Comment by hammer** [comment]
We should consider an inline comment form so that we don't have to pop out and disrupt the table
