### ISSUE TITLE
Who are we building CycleDash for?

### ISSUE THREAD

**Issue by jaclynperrone** [hammerlab/cycledash#654]
While our user base may change throughout the life of CycleDash, I'd like to focus on who we are trying to serve in this current phase of the product. 

Who are our power users and how do we determine what they want?

**Comment by hammer** [comment]
> Who are our power users

A power user is someone who is an effective user of modern web applications and has meaningful genomics domain knowledge.

I think Cyriac Kandoth and Andrew Uzilov are our two best model users right now.

An additional question to answer: **what are our power users trying to do**?

I have a few answers:

1. Build a better somatic variant caller
1. Given a sample, produce a list of high-confidence somatic variant calls
1. Given a list of variant calls, determine the phenotype of the cell/tissue/patient
1. Given an organization made of many teams, keep track of all projects, patients, and samples being analyzed by all teams in the organization.

**Comment by jaclynperrone** [comment]
I'm looking forward to talking more about this today. I've certainly been hearing a mixed bag of responses throughout this interview process with different researchers. Some say to focus on those developing new variant callers (I believe that touches on `#1`?), others say to help the "computationally illiterate" make, save and share filters (and I know where you stand on that one :smile:). Just interesting stuff. And I think we would be doing ourselves a disservice if we didn't consider these other insights.

My only hesitation with focusing on users like Cyriac & Andrew, is that by the nature of them being "power users", they already have their own workflows that have been tried and true. How do we get them to take on another tool that could potentially deviate them from that? Also, when I talked to Cyriac, he was saying how the Cycledash workflow (manually filtering variants and viewing them in a pileup, for example) is something he hasn't been doing for a while now. He has gotten to a point where everything is automated. That aside, I think my chat with Andrew in the coming weeks will shed more light on the kind of work a user like him has been up to.

I think it would be interesting to talk about Cycledash in a few phases. At our first check-in we talked about focusing on getting the upstream analysis right (phase 1). And once we tackle that problem, then onto the bigger fishes downstream (:fishing_pole_and_fish:). I think building a solid foundation and reputation to start is a good first step. So let's talk later about how we know we've accomplished phase 1, and who we should be targeting along the way.

**Comment by jaclynperrone** [comment]
Also! I want to poke at this:
> A power user is someone who is an effective user of modern web applications and has meaningful genomics domain knowledge.

Let's break this down a little bit. Let's talk about what constitutes as "effective", "modern" and "meaningful".

**Comment by hammer** [comment]
> My only hesitation with focusing on users like Cyriac & Andrew, is that by the nature of them being "power users", they already have their own workflows that have been tried and true. How do we get them to take on another tool that could potentially deviate them from that?

The wonderful thing about academia is that there is a high level of turnover in staff. Also, the genomics market is growing rapidly. Existing organizations need to replace Cyriacs and Andrews regularly, and new organizations need to grow their own. Current workflows are highly suboptimal, so while they may be "tried", I don't think they're very "true".

**Comment by jaclynperrone** [comment]
But why are they suboptimal? They seem to be working really well for the kind of users we are targeting.

**Comment by hammer** [comment]
> They seem to be working really well

I have a far different perception of how well they're working. Why do you think existing workflows work well?

**Comment by jaclynperrone** [comment]
Well, the more advanced researchers gave positive reactions when talking about their own workflows. They were proud of how much they could automate and customize it. I see what you are saying though. This kind of tailored workflow is not scalable and hard to share with the community at large. But there is something about how they appreciate the automation. Even Cyriac was saying that people would use CycleDash if it just ran their scripts/processes for them, and Arman mentioned how it would be great if BAM/VCFs could just be automatically uploaded to Cycledash when they are ready.

**Comment by jaclynperrone** [comment]
The negative reactions when talking about workflow came when researchers like Nicole or Leo had to manually inspect variants and communicate those findings to the rest of their team.

**Comment by ihodes** [comment]
My goal in working on Cycledash has been to aid in the pursuit of "Build(ing) a better somatic variant caller". This has guided feature and architecture choices made like histograms, variant density map on the karyogram, the most prominent field names having to do with the variant caller being used and parameters it was called with, etc.

It seems like we want to target a larger set of users than are building somatic variant callers in order to reach the desired success states. We can try to support various types of users, and that may be a reasonable thing to do at some point, but I think focusing on one large set of users (with an eye on the rest), with a few specific users of that group to stay closely in contact with, would be ideal.

The primary strength of Cycledash is in aiding in the manual inspection of variants calls. I want to be sure not to target users who shouldn't be doing the manual inspections that Cycledash facilitates.

**Comment by hammer** [comment]
I think we're talking about two separate things. Whether someone is happy with their current workflow, and whether it's a good workflow. Even if the former is true the latter can be false.

> Arman mentioned how it would be great if BAM/VCFs could just be automatically uploaded to Cycledash when they are ready.

I think this would be great, for core facilities to dump FASTQs into Cycledash and have us take over from there. I actually think Arman's point is in support of a new workflow.

**Comment by jaclynperrone** [comment]
It all sounds so subjective to me. I think we should define what we think a "good" workflow is, and talk to people in the field about it.

**Comment by hammer** [comment]
> I think we should define what we think a "good" workflow

Absolutely.

> talk to people in the field about it.

Sure, with a giant caveat that I don't want to build faster horses. I don't think many people in the field have had exposure to modern data management tools, so they don't know that they're suboptimal or even how to imagine something better. We can't be totally customer-driven; our vision is an important ingredient of the design.

**Comment by jaclynperrone** [comment]
Yeah I hear you. And it's helpful to have that distinction!

**Comment by jaclynperrone** [comment]
I'm going to close this one on account of the meeting we had. We said that the goal of this first phase would be to help users produce a list of high-confidence somatic variant calls from a sample.
