### ISSUE TITLE
Tasks pages have lost styling

### ISSUE THREAD

**Issue by ihodes** [hammerlab/cycledash#665]
e.g. http://cycledash.demeter.hpc.mssm.edu/runs/320/tasks

![](https://d1zjcuqflbd5k.cloudfront.net/files/acc_204365/1ihz0?response-content-disposition=inline;%20filename=Screen%20Shot%202015-06-01%20at%2017.14.08.png&Expires=1433193308&Signature=MRxfq8Tnc0Cdxzn5ynh2Ny1VU4Nfn7gBbZMScEQCw2XZOpzSuEVVu5eHeaDTVwrDfnqGd21CVI9oMEH5tfawXDwjEAOGu2W2UGgYca0r83YntiLj-HBUcudl3JIfPd0gReM9ZEIxkRAWuu-2s69-0WA2QkpMBukyQh-Vlzjd4P4_&Key-Pair-Id=APKAJTEIOJM3LSMN33SA)

**Comment by jaclynperrone** [comment]
#676 closes this!
