### ISSUE TITLE
BAM/RUNs form overlaps project notes

### ISSUE THREAD

**Issue by ihodes** [hammerlab/cycledash#670]
![screen shot 2015-06-01 at 17 36 30](https://cloud.githubusercontent.com/assets/167803/7941104/ecfbda7a-0922-11e5-85b6-7867a7c3bc9a.png)

**Comment by jaclynperrone** [comment]
Thanks for the screenshot! I'm going to assign this one to myself.

**Comment by jaclynperrone** [comment]
Hey @ihodes, the screenshot is 404ing. Would you mind resubmitting it? Also, can you walk me through how you got this bug? :nyan:

**Comment by ihodes** [comment]
Screenshot fixed; Bug can be reproduced by click on the "Add BAM" or "Add Run" button on a project with a note.
