### ISSUE TITLE
A user should be able to flag a variant

### ISSUE THREAD

**Issue by jaclynperrone** [hammerlab/cycledash#675]
Right now comments are used as a way to both [1] flag a variant and [2] add a blurb about it. But these two actions serve two different purposes. This issue is about factoring out that desire to flag a variant for later inspection, and leaving the comment for...well, commenting (and reporting: #674)

This needs design, but it would act like a "favoriting" mechanism.

**Comment by jaclynperrone** [comment]
Here's a design that features stars as flags**[1]**. An empty star will show up on hover, and when the user clicks it, it will fill in and always be visible. When a user clicks on a filled-in star, it will turn to the outlined version and disappear on mouse-out. 

**[1]**
![1-table-stars](https://cloud.githubusercontent.com/assets/5685044/9772279/2193478a-5709-11e5-835e-760bb25fa154.png)

**Comment by ihodes** [comment]
When I read the user interviews, I recall that users wanted to flag variants with certain terms (e.g. "this is a mistake" or "this could be driving the cancer!"; obviously the flag text or symbol would be shorter.) The UI for that is obviously trickier to get right. Without users, I can see that doing something more complicated than a on/off flag might be fraught. This could be a reasonable first step, though I'm not sure I'd know, as a user, what a star was meant to signify.

**Comment by ihodes** [comment]
Also, ever the space-saver, I'm concerned about shifting over the table another 20+ px! (There's undoubtedly a lot more we can do to shrink this table, like moving comment counts in the bubble + not showing all the info/sample/filter/quality etc columns by default).

**Comment by jaclynperrone** [comment]
Thanks for the feedback! This flagging/starring is about giving users a quick way to mark whichever variants they'd like to remember for later. This is a baby step in getting to #674, which talks about adding in those terms you mentioned.

I'm not too concerned about the extra px. We can certainly make it work!
