### ISSUE TITLE
Opening pileup.js crashing tab

### ISSUE THREAD

**Issue by ihodes** [hammerlab/cycledash#697]
On run, i click e.g. the third row and open pileup viewer. I don't see any errors, and I'm unable to collect a profile (tab crashes, won't recover). http://cycledash.demeter.hpc.mssm.edu/runs/226/examine?query=ORDER+BY+contig%2C+position

**Comment by danvk** [comment]
I can reproduce this. It seems to be an infinite loop in the BAM fetching code.

**Comment by danvk** [comment]
The problematic fetch is `chr20:2684600-2684800` in `http://hammerlab-dev3.hpc.mssm.edu:9876/datasets/martignetti_ovarian/189/Illumina_RNA/QC_S106.B202_PCT189_RNA.PE.RNASeqRibozero.RAPiD.Human/PT_189_Left_Ovary_RNA/Processed/RAPiD.2_0_0/bams/PT_189_Left_Ovary_RNA.accepted_hits.sort.coord.bam`
