### ISSUE TITLE
Implement a new worker for Cycledash that will annotate Protein-level changes for a given variant/VCF file

### ISSUE THREAD

**Issue by hammer** [hammerlab/cycledash#699]
As noted in @armish's status report.

**Comment by armish** [comment]
thanks @hammer -- will get this done with our 0.2.0 milestone.

**Comment by armish** [comment]
this is done as of https://github.com/hammerlab/cycledash/commit/cc9d8c03a950df0620a7e695e33c4ffbaea5f248 (a.k.a. PR #750)
