### ISSUE TITLE
The project notes paragraph should not appear if there are no notes

### ISSUE THREAD

**Issue by jaclynperrone** [hammerlab/cycledash#728]
Right now, the `p.notes` block appears in the Project card even if it is empty. Let's just not have it show up at all if there are no notes. This will allow me to add a `margin-top` to it, which I can't do now without it throwing the layout off.
![p notes](https://cloud.githubusercontent.com/assets/5685044/8165728/ca0613f8-1360-11e5-8bbf-87736637a943.png)

**Comment by hammer** [comment]
Super terse
