### ISSUE TITLE
Suppress empty columns in variants table?

### ISSUE THREAD

**Issue by danvk** [hammerlab/cycledash#729]
I'm not sure what "Quality" and "Filters" mean, but for this run they take up quite a bit of horizontal space and don't have any values:

![empty columns](https://cloud.githubusercontent.com/assets/98301/8166376/6fcbb870-1365-11e5-8a38-f22bda4bfbc3.png)

(via [run 235][1])

[1]: http://cycledash.demeter.hpc.mssm.edu/runs/235/examine

**Comment by danvk** [comment]
cc @jaclynperrone

**Comment by ihodes** [comment]
IIRC there's an issue filed for this already. It's specifically an issue with Quality and Filter. These are two columns found in all VCFs—quality of the variants and the filters applied/filtering it out.

**Comment by danvk** [comment]
#555
