### ISSUE TITLE
"Linked Bams" need to have separator between them

### ISSUE THREAD

**Issue by ihodes** [hammerlab/cycledash#734]
e.g. http://d.pr/i/1d59J

**Comment by jaclynperrone** [comment]
@ihodes This one only needs a line of CSS tweaked. Do I create a PR for it? Or should I just push it to master?

**Comment by ihodes** [comment]
I'd still do a PR. Nice to have records, sequence, changes, etc.

**Comment by jaclynperrone** [comment]
Cool. Makes sense!
