### ISSUE TITLE
view > 2 pileups at once

### ISSUE THREAD

**Issue by timodonnell** [hammerlab/cycledash#739]
For example, other tumor samples from the sample patient, or RNA-seq

**Comment by hammer** [comment]
Cf. #735

**Comment by ihodes** [comment]
Cf. #790

**Comment by danvk** [comment]
Is this possible now? (Not sure why this was closed)

**Comment by ihodes** [comment]
@danvk it's a dup of the linked issue (though now I see the linked issue is actually the dup!)
