### ISSUE TITLE
Clicking a BAM file in the table causes an odd-resizing

### ISSUE THREAD

**Issue by arahuja** [hammerlab/cycledash#743]
Original table:
![image](https://cloud.githubusercontent.com/assets/455755/8187745/99e7652c-141f-11e5-9906-44889831bfc7.png)

After click a single row:
![image](https://cloud.githubusercontent.com/assets/455755/8187755/a78fac48-141f-11e5-9fd8-970a4d72a5bc.png)

**Comment by danvk** [comment]
@jaclynperrone sounds like a CSS bug
