### ISSUE TITLE
pileup tracks scroll vertically

### ISSUE THREAD

**Issue by danvk** [hammerlab/cycledash#805]
The location, scale, genome and VCF tracks all scroll by a few pixels. They shouldn't:

![cycledash updated](https://cloud.githubusercontent.com/assets/98301/9048043/186b067e-3a04-11e5-9bec-cf4012de8bc4.png)

There seem to be 5px of mysterious vertical space in the `<div>` that contains each `<svg>` element.

**Comment by armish** [comment]
I didn't know this before, but after some fiddling I was able to isolate the problem into this one:
http://jsfiddle.net/yh7L7wwa/

and learned found [a trick on SO](http://stackoverflow.com/questions/24626908/how-to-get-rid-of-extra-space-below-svg-in-div-element) to get rid of the space there:
http://jsfiddle.net/yh7L7wwa/1/

Looks like we need to give the examine page some CSS love (will do).

**Comment by armish** [comment]
addressed by #811.
