### ISSUE TITLE
VCF comparison table showing incorrect results

### ISSUE THREAD

**Issue by jaclynperrone** [hammerlab/cycledash#822]
I tried a couple comparisons on http://cycledash.demeter.hpc.mssm.edu/ and the table is showing incorrect values for True Positives
![compare1](https://cloud.githubusercontent.com/assets/5685044/9584266/3bc2fa6a-4fde-11e5-8904-f83f322a9289.png)

**Comment by ihodes** [comment]
Could you link the run this is seen on?

**Comment by jaclynperrone** [comment]
Surely! 
http://cycledash.demeter.hpc.mssm.edu/runs/267/examine?query=ORDER+BY+contig%2C+position

**Comment by ihodes** [comment]
False negatives tentatively look correct (the false negatives are variants which are found in the VCF being compared to, but not in the variants you're examining). True positives bear some looking into.
