### ISSUE TITLE
Make Cycledash useful for PGV

### ISSUE THREAD

**Issue by hammer** [hammerlab/cycledash#852]
Umbrella issue for features that make Cycledash a better tool for the PGV team's quest to call somatic mutations faster.

**Comment by hammer** [comment]
I believe @ihodes volunteered at the offsite to lead this effort with @iskandr.

**Comment by ihodes** [comment]
Yes, let's do this.

**Comment by iskandr** [comment]
Maybe we can start some of the conversation here. 

Questions:

1) How do we deal with multiple views of the same sequencing run? We'll have 4 VCFs for each tumor sample (2x aligners, 2x variant callers) -- will we be able to combine those in a s single page? 

2) Do we want to place any access restriction on who can see data from PGV patients? 

3) ... while still making it easy for collaborators outside the lab to see the data & leave comments. 

4) PGV relies on allele-specific quantification of expression from RNAseq, how can that data be shown in Cycledash?

5) Do we want to show epitope predictions in Cycledash?

6) Do we want to show the vaccine peptides in Cycledash?

From a reviewer's point of view, the most important workflow will probably be "look at the top k vaccine peptide predictions and make sense they're both plausibly supported by the data and correctly ranked".

**Comment by hammer** [comment]
Given the time constraint it's probably time to try out SNAP (cf. https://github.com/hammerlab/biokepi/issues/2). @arahuja have you tried SNAP again recently?

**Comment by hammer** [comment]
> 4) PGV relies on allele-specific quantification of expression from RNAseq, how can that data be shown in Cycledash?

Seems like a worker + a new column would work just fine

**Comment by ihodes** [comment]
> 1) How do we deal with multiple views of the same sequencing run? We'll have 4 VCFs for each tumor sample (2x aligners, 2x variant callers) -- will we be able to combine those in a s single page?

Definitely; this is a feature we've been wanting to add for a while, so I'm glad it's a requirement of this project. Lots of features along these lines filed: https://github.com/hammerlab/cycledash/issues?utf8=✓&q=is%3Aissue+is%3Aopen+compare+

> 2) Do we want to place any access restriction on who can see data from PGV patients?

This also seems reasonable: https://github.com/hammerlab/cycledash/issues/770

> 3) ... while still making it easy for collaborators outside the lab to see the data & leave comments.

Our ACL should support access at run-level granularity.

> 4) PGV relies on allele-specific quantification of expression from RNAseq, how can that data be shown in Cycledash?

Cf. @hammer's response, that seems like a quick reasonable way of handling this.

> 5) Do we want to show epitope predictions in Cycledash?
> 6) Do we want to show the vaccine peptides in Cycledash?

These are tougher; this may require a new view to handle nicely, which is probably in-scope for Cycledash. We should be able to support other datatypes and custom visualizations in a pluggable fashion. This is something I'd see as a longer-term feature if we can get moving without it.

> From a reviewer's point of view, the most important workflow will probably be "look at the top k vaccine peptide predictions and make sense they're both plausibly supported by the data and correctly ranked".

To support this without 5 & 6 right away we could add a column & worker that somehow ranks mutations based on the interestingness of the vaccine peptides they are found in—definitely something we should chat more about on Monday.

**Comment by ihodes** [comment]
Data to track https://github.com/hammerlab/pgv/issues/1

**Comment by ihodes** [comment]
https://github.com/hammerlab/cycledash/milestones/Ready%20for%20PGV tracks what's required to make Cycledash ready for PGV.
